name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
  merge_group:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@0cde4689ba33c09f1b890c1725572ad96751a3fc # v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      - name: Bootstrap
        run: script/bootstrap
        env:
          SKIP_BUNDLER: true
      - name: Tests
        run: script/test
